### ISSUE TITLE
"What next" Return to module (Aug 2020)

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/rock-band#204]
We've had feedback from a user who would like the option to return to the Code Club module they were working through at the end of each project.

We do link through to the next project each time but it's not necessarily clear that it is the next one along. Perhaps it would be nice for us also to link back to the module even if just so the user can get a view of progression. 

https://projects.raspberrypi.org/en/projects/chatbot/8

**Comment by rik-cross** [comment]
I think this is a broader issue that will probably be addressed as we develop pathways into the project site more fully. We'll hopefully have 'what's next' sections that signpost the pathway, the next project in the pathway, etc.

If others agree, might be worth closing this and revisiting if we think the upcoming pathway work doesn't fix this.
